### ISSUE TITLE
Suspected Mishap Wrecks Build

### ISSUE THREAD

**Issue by AlmightyLks** [Gratt-5r2/UnionProject#1]
https://github.com/Gratt-5r2/UnionProject/blob/3c2e1a41eb2f3ca47caf9fbd031fbdb371b3818c/UnionProject/GothicAPI/Gothic_I_Classic/API/oNpc.h#L320-L322

The "Enable" seems out of place + is the cause of the project not compiling
Unintentional?

**Comment by Gratt-5r2** [comment]
`oCNpc::Enable(zVEC3)` function used for activation an NPC in the current game world. At the argument your should specify the point where X - `right` axis, Y - `top` axis, Z - `at` axis. 

`oEFightAction` is the part of the `oCNpc` class. Used in the Fight AI. You can get access to the elements of this enum like `oCNpc::oEFightAction::NPC_FIGHTMOVE_RUN` or `oCNpc::NPC_FIGHTMOVE_RUN`.

**Comment by AlmightyLks** [comment]
Mind having a peek at the lines of code I have shared for that?

The definition of oNPC::Enable seems to have nothing to do with the faulty definition of the oEFightAction enum 😅

**Comment by Gratt-5r2** [comment]
> Mind having a peek at the lines of code I have shared for that?

Here the problem is in the including order of the header files, more precisely in the package (or arguments) with which you trying to compile the Gothic API.

> The definition of oNPC::Enable seems to have nothing to do with the faulty definition of the oEFightAction enum 😅

Absolutely nothing.

**Comment by AlmightyLks** [comment]
> Here the problem is in the including order of the header files, more precisely in the package (or arguments) with which you trying to compile the Gothic API.

Oh, thanks for the hint. That gave me an idea, but anyhow the mention of this issue, within the other issue is unrelated 😄 

I feel like there is a miscommunication, and the code snippet I shared initially may not pronounce it as much
![image](https://user-images.githubusercontent.com/54688434/185459080-add53528-0f38-4b39-816d-273c682195d0.png)

Are you sure this is right?

**Comment by Gratt-5r2** [comment]
Oops, from the mobile phone this part was not visible for me, sorry. But I have no idea why this is there :) Looks like a misclick. Please check it now.

**Comment by AlmightyLks** [comment]
Glad we sorted it out 😄 
Are you going to push a fix, or should I do a quick PR?

**Comment by AlmightyLks** [comment]
Resolved in [99ac1e8](https://github.com/Gratt-5r2/UnionProject/commit/99ac1e8a082babfd83571629dc300a1be0b9e6d9)
